import "bootstrap/dist/css/bootstrap.css";
import "../styles/globals.css";
import SubBar from "../components/SubBar";
import type { AppProps } from "next/app";
import Head from "next/head";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SubBar />
      <Component {...pageProps} />
    </div>
  );
}

export default MyApp;
