import SubBar from "../components/SubBar";
import DocsComponent from "../components/DocsComponent";
import Head from "next/head";

const Docs = () => {
  return (
    <div>
      <Head>
        <title>Descargar documentación</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SubBar />
      <DocsComponent />
    </div>
  );
};
export default Docs;
