import MainComponet from "../components/MainComponet";
import SubBar from "../components/SubBar";
import Head from "next/head";

const Main = () => {
  return (
    <div>
      <Head>
        <title>Mejor casarse que abrasarse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SubBar />
      <MainComponet />
    </div>
  );
};

export default Main;
