import MesterComponet from "../components/MesterComponent";
import SubBar from "../components/SubBar";
import Head from "next/head";
import Footer from "../components/Footer";

const Mester = () => {
  return (
    <div>
      <Head>
        <title>Mester de Algarabía</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SubBar />
      <MesterComponet />
      <Footer />
    </div>
  );
};
export default Mester;
