import SubBar from "../components/SubBar";
import SpeachComponet from "../components/SpeachComponet";
import Head from "next/head";
import Footer from "../components/Footer";

const Speach = () => {
  return (
    <div>
      <Head>
        <title>Fechas de charlas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/medieval.png" />
      </Head>
      <SubBar />
      <SpeachComponet />
      <Footer />
    </div>
  );
};

export default Speach;
